cameras:
- camera_id: 0
  id: 1
  roi:
    x1: 128
    x2: 1613
    y1: 242
    y2: 914
- camera_id: 1
  id: 2
  roi:
    x1: 432
    x2: 1553
    y1: 169
    y2: 843
# - camera_id: 2
#   id: 3
#   roi:
#     x1: 464
#     x2: 1522
#     y1: 258
#     y2: 842
# - camera_id: 3
#   id: 4
#   roi:
#     x1: 506
#     x2: 1640
#     y1: 198
#     y2: 935
